# place holder

In [1]:
import numpy
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
X_1 = tf.compat.v1.placeholder(tf.float32, name = "X_1")
X_2 = tf.compat.v1.placeholder(tf.float32, name = "X_2")
multiply = tf.multiply(X_1, X_2, name = "multiply")
with tf.compat.v1.Session() as session:
    result = session.run(multiply, feed_dict={X_1:[1,2,3], X_2:[4,5,6]})
    print(result)

[ 4. 10. 18.]


In [2]:
import numpy as np
x_input=np.random.sample((1,2))
x = tf.compat.v1.placeholder(tf.float32, shape=[1,2], name = 'X')
dataset = tf.compat.v1.data.Dataset.from_tensor_slices(x)
iterator = dataset.make_initializable_iterator()
get_next = iterator.get_next()
with tf.compat.v1.Session() as sess:
    # feed the placeholder with data
    sess.run(iterator.initializer, feed_dict={ x: x_input })
    print(sess.run(get_next)) # output [ 0.52374458  0.71968478]

Instructions for updating:
This is a deprecated API that should only be used in TF 1 graph mode and legacy TF 2 graph mode available through `tf.compat.v1`. In all other situations -- namely, eager mode and inside `tf.function` -- you can consume dataset elements using `for elem in dataset: ...` or by explicitly creating iterator via `iterator = iter(dataset)` and fetching its elements via `values = next(iterator)`. Furthermore, this API is not available in TF 2. During the transition from TF 1 to TF 2 you can use `tf.compat.v1.data.make_initializable_iterator(dataset)` to create a TF 1 graph mode style iterator for a dataset created through TF 2 APIs. Note that this should be a transient state of your code base as there are in general no guarantees about the interoperability of TF 1 and TF 2 code.
[0.25593743 0.2677976 ]


In [29]:
tf.compat.v1.disable_eager_execution()
p2=tf.compat.v1.placeholder(tf.float32)
p1=tf.compat.v1.placeholder(tf.float32)
with tf.compat.v1.Session() as sess:
    print(sess.run([p1+p2,p1*p2],feed_dict={p1:10,p2:20}))

[30.0, 200.0]


# constant

In [16]:
import tensorflow as tf
r1_decimal =  tf.constant([ [1, 2],[3, 4] ],tf.int16,name='a')
r2_decimal= tf.constant([ [1, 1],[3, 4] ],tf.float32,name='b')
print(r1_decimal)
print(r2_decimal)
print(tf.cast(r1_decimal,tf.float32)+r2_decimal)
#sess = tf.compat.v1.Session()
#with sess.as_default():
    #print(r1_decimal)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int16)
tf.Tensor(
[[1. 1.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 3.]
 [6. 8.]], shape=(2, 2), dtype=float32)


In [16]:
tensor_const=tf.constant([[10, 20],[30, 40]])
var_init_2 = tf.compat.v1.get_variable("var_init_2", dtype=tf.int32,  initializer=tensor_const)
print(var_init_2.shape)

(2, 2)


In [47]:
x=tf.constant([1])
y=tf.constant([2])
mul=tf.multiply(x, y)
print(mul)
with tf.compat.v1.Session() as session:
    result=session.run( tf.multiply(x, y))
    print(result)

Tensor("Mul_9:0", shape=(1,), dtype=int32)
[2]


# variable

In [3]:
a=tf.compat.v1.Variable(name='b',initial_value=20)
#sess=tf.compat.v1.Session()
with tf.compat.v1.Session() as sess:
    #sess.run(a.initializer) #khởi tạo
    #print(sess.run(a))
    sess.run(tf.compat.v1.global_variables_initializer())
    print(sess.run(a))

20
